version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: percobaan8_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-p8user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p8pass}
      POSTGRES_DB: ${POSTGRES_DB:-percobaan8}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata_p8:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-p8user} -d ${POSTGRES_DB:-percobaan8}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_p8:
