moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - dobot_arm_controller

  dobot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - magician_joint_1
      - magician_joint_2
      - magician_joint_3
      - magician_joint_4