# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dobot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dobot_arm_controller:
  ros__parameters:
    joints:
      - magician_joint_1
      - magician_joint_2
      - magician_joint_3
      - magician_joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - magician_joint_prismatic_l
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity